<?php

return [
    'admin' => [
        'safe_tables' => [
            'orders',
            'order_items',
            'payment_logs',
            'boats',
            'homestays',
            'culinaries',
            'paket_culinaries',
            'kiosks',
            'paket_wisatas',
            'paket_wisata_boat',
            'paket_wisata_homestay',
            'paket_wisata_culinary',
            'paket_wisata_kiosk',
            'paket_wisata_destinasi',
            'beban_operasionals',
            'ai_chat_logs',
        ],
        'safe_columns' => [
            'orders' => [
                'id_order',
                'customer_name',
                'customer_email',
                'customer_phone',
                'base_amount',
                'total_amount',
                'payment_method',
                'status',
                'paid_at',
                'refund_amount',
                'refund_fee',
                'refund_status',
                'created_at',
            ],
            'order_items' => [
                'id_order',
                'id_paket',
                'nama_paket',
                'durasi_hari',
                'jumlah_peserta',
                'tanggal_keberangkatan',
                'subtotal',
                'vendor_cost_total',
                'company_profit_total',
            ],
            'boats' => ['id', 'id_boat', 'nama', 'kapasitas', 'harga_sewa', 'is_active'],
            'homestays' => ['id_homestay', 'nama', 'kapasitas', 'harga_per_malam', 'is_active'],
            'culinaries' => ['id_culinary', 'nama', 'lokasi', 'deskripsi'],
            'paket_culinaries' => ['id', 'id_culinary', 'nama_paket', 'kapasitas', 'harga'],
            'kiosks' => ['id_kiosk', 'nama', 'kapasitas', 'harga_per_paket', 'deskripsi'],
            'paket_wisatas' => [
                'id_paket',
                'nama_paket',
                'durasi_hari',
                'minimum_participants',
                'maximum_participants',
                'harga_total',
                'harga_jual',
                'harga_final',
                'status',
            ],
            'beban_operasionals' => ['kode_transaksi', 'tanggal', 'kategori', 'deskripsi', 'jumlah', 'metode_pembayaran'],
            'ai_chat_logs' => ['session_id', 'admin_id', 'role', 'message', 'intent', 'context_json', 'created_at'],
        ],
        'domains' => [
            'booking' => [
                'label' => 'Booking & Orders',
                'description' => 'Sumber data transaksi utama, status pembayaran, refund, peserta, dan histori pemesanan.',
                'tables' => ['orders', 'order_items', 'payment_logs'],
                'business_terms' => ['order', 'booking', 'refund', 'payment', 'peserta', 'keberangkatan'],
            ],
            'resources' => [
                'label' => 'Resources',
                'description' => 'Master resource operasional yang dipakai paket: boat, homestay, culinary, kiosk.',
                'tables' => ['boats', 'homestays', 'culinaries', 'paket_culinaries', 'kiosks'],
                'business_terms' => ['boat', 'kapal', 'homestay', 'culinary', 'kuliner', 'kiosk', 'resource', 'kapasitas'],
            ],
            'packages' => [
                'label' => 'Packages',
                'description' => 'Produk wisata yang menggabungkan banyak resource, harga jual, harga modal, dan itinerary.',
                'tables' => ['paket_wisatas', 'paket_wisata_boat', 'paket_wisata_homestay', 'paket_wisata_culinary', 'paket_wisata_kiosk', 'paket_wisata_destinasi'],
                'business_terms' => ['paket', 'package', 'tour package', 'itinerary', 'margin'],
            ],
            'finance' => [
                'label' => 'Finance',
                'description' => 'Revenue, cost of sales, profit, refund, cash flow, dan beban operasional.',
                'tables' => ['orders', 'order_items', 'beban_operasionals'],
                'business_terms' => ['keuangan', 'finance', 'revenue', 'profit', 'cash flow', 'expense', 'beban operasional'],
            ],
            'ai_audit' => [
                'label' => 'AI Audit',
                'description' => 'Riwayat sesi chat admin dan metadata jawaban AI untuk audit dan memory percakapan.',
                'tables' => ['ai_chat_logs'],
                'business_terms' => ['ai chat', 'riwayat', 'history', 'session', 'audit'],
            ],
        ],
        'entities' => [
            'boat' => [
                'label' => 'Boat',
                'table' => 'boats',
                'key' => 'id_boat',
                'name_column' => 'nama',
                'aliases' => ['boat', 'kapal', 'armada'],
            ],
            'homestay' => [
                'label' => 'Homestay',
                'table' => 'homestays',
                'key' => 'id_homestay',
                'name_column' => 'nama',
                'aliases' => ['homestay', 'penginapan', 'room', 'kamar'],
            ],
            'culinary' => [
                'label' => 'Culinary',
                'table' => 'culinaries',
                'key' => 'id_culinary',
                'name_column' => 'nama',
                'aliases' => ['culinary', 'kuliner', 'makanan', 'food'],
            ],
            'kiosk' => [
                'label' => 'Kiosk',
                'table' => 'kiosks',
                'key' => 'id_kiosk',
                'name_column' => 'nama',
                'aliases' => ['kiosk', 'kedai', 'booth'],
            ],
            'package' => [
                'label' => 'Package',
                'table' => 'paket_wisatas',
                'key' => 'id_paket',
                'name_column' => 'nama_paket',
                'aliases' => ['paket', 'package', 'tour package', 'trip'],
            ],
            'expense' => [
                'label' => 'Operational Expense',
                'table' => 'beban_operasionals',
                'key' => 'kode_transaksi',
                'name_column' => 'deskripsi',
                'aliases' => ['expense', 'beban', 'operasional'],
            ],
        ],
    ],
];
